name: Code checks

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  run-code-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.x'

      - name: Install system dependencies
        run: pip3 install pipenv

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs/
          key: ${{ runner.os }}-python-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Python dependencies
        run: pipenv install --dev --deploy

      - name: Run type checking
        run: make type

      - name: Run lint tools
        run: make check-lint
